server:
  port: 56081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank1?useUnicode=true
    data-username: root
    password: 1234

rocketmq:
  producer:
    group: producer_bank1
  name-server: 127.0.0.1:9876